CREATE TABLE USER (
id VARCHAR(255) PRIMARY KEY,
username VARCHAR(67) NOT NULL,
password VARCHAR(255) NOT NULL,
email VARCHAR(128) NOT NULL,
status ENUM("active", "inactive") NOT NULL
);

CREATE TABLE SUPERUSER (
id VARCHAR(255) PRIMARY KEY,
permissions ENUM("total", "create", "edit", "read", "none") NOT NULL,
CONSTRAINT fk_superuser FOREIGN KEY (id)
REFERENCES USER(id)
ON DELETE CASCADE
);

CREATE TABLE SUBSCRIPTION (
id VARCHAR(255) PRIMARY KEY,
userId VARCHAR(255) NOT NULL,
startDate DATE NOT NULL,
endDate DATE NOT NULL,
status ENUM("active", "expired") NOT NULL,
type ENUM("standard", "premium", "standard_yearly", "premium_yearly") NOT NULL,
CONSTRAINT fk_sub_user FOREIGN KEY (userId)
REFERENCES USER(id)
ON DELETE CASCADE
);

CREATE TABLE PAYMENT (
id VARCHAR(255) PRIMARY KEY,
subscriptionId VARCHAR(255) NOT NULL,
paymentDate DATE NOT NULL,
method ENUM("card", "paypal") NOT NULL,
status ENUM("pending", "completed", "failed") NOT NULL,
CONSTRAINT fk_pm_cliente FOREIGN KEY (subscriptionId)
REFERENCES SUBSCRIPTION(id)
ON DELETE CASCADE
);
CREATE TABLE PROFILE (
id VARCHAR(255) PRIMARY KEY,
userId VARCHAR(255) NOT NULL,
CONSTRAINT fk_profile_user FOREIGN KEY (userId)
REFERENCES USER(id)
ON DELETE CASCADE
);

CREATE TABLE CONTENT (
id VARCHAR(255) PRIMARY KEY,
title VARCHAR(200) NOT NULL,
description VARCHAR(255),
duration INT NOT NULL,
ageRating VARCHAR(10) NOT NULL,
coverUrl VARCHAR(255),
videoUrl VARCHAR(255),
type ENUM("series", "movie", "documentary") NOT NULL
);

CREATE TABLE HISTORY (
profileId VARCHAR(255) NOT NULL,
contentId VARCHAR(255) NOT NULL,
lastWatched DATETIME NOT NULL,
timeViewed INT NOT NULL,
PRIMARY KEY (profileId, contentId),
CONSTRAINT fk_hist_profile FOREIGN KEY (profileId)
REFERENCES PROFILE(id)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT fk_hist_content FOREIGN KEY (contentId)
REFERENCES CONTENT(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE FAVORITE (
profileId VARCHAR(255) NOT NULL,
contentId VARCHAR(255) NOT NULL,
addedDate DATE NOT NULL,
PRIMARY KEY (profileId, contentId),
CONSTRAINT fk_fav_profile FOREIGN KEY (profileId)
REFERENCES PROFILE(id)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT fk_fav_content FOREIGN KEY (contentId)
REFERENCES CONTENT(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE RATING (
profileId VARCHAR(255) NOT NULL,
contentId VARCHAR(255) NOT NULL,
rating ENUM("like", "dislike", "unrated") DEFAULT "unrated" NOT NULL,
PRIMARY KEY (profileId, contentId),
CONSTRAINT fk_rating_profile FOREIGN KEY (profileId)
REFERENCES PROFILE(id)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT fk_rating_content FOREIGN KEY (contentId)
REFERENCES CONTENT(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE GENRE (
id VARCHAR(255) PRIMARY KEY,
name VARCHAR(67) NOT NULL
);

CREATE TABLE CONTENT_GENRE (
contentId VARCHAR(255) NOT NULL,
genreId VARCHAR(255) NOT NULL,
PRIMARY KEY (contentId, genreId),
CONSTRAINT fk_cg_content FOREIGN KEY (contentId)
REFERENCES CONTENT(id)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT fk_cg_genre FOREIGN KEY (genreId)
REFERENCES GENRE(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);
