CREATE TABLE USUARIO (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(67) NOT NULL,
contraseña VARCHAR(41) NOT NULL,
correo VARCHAR(128) NOT NULL,
estado ENUM ("activo", "inactivo") NOT NULL
);

CREATE TABLE SUPERUSUARIO (
id INT PRIMARY KEY,
permisos ENUM ("total", "crear", "editar", "consultas", "ninguno")NOT NULL,
CONSTRAINT fk_super_usuario FOREIGN KEY (id)
REFERENCES USUARIO(id)
ON DELETE CASCADE
);

CREATE TABLE CLIENTE (
Id INT PRIMARY KEY,
CONSTRAINT fk_cliente FOREIGN KEY (id)
REFERENCES USUARIO(id)
ON DELETE CASCADE
);

CREATE TABLE SUSCRIPCION(
id INT AUTO_INCREMENT PRIMARY KEY,
fechaInicio DATE NOT NULL,
fechaFin DATE NOT NULL,
estado ENUM ("activa", "caducada") NOT NULL,
tipo ENUM ("estandar", "premium", "estandar_anual", "premium_anual") NOT NULL

);

CREATE TABLE CLIENTE_SUSCRIPCION (
idCliente INT NOT NULL,
idSuscripcion INT NOT NULL,
PRIMARY KEY (idCliente, idSuscripcion),
CONSTRAINT fk_cs_cliente FOREIGN KEY (idCliente)
REFERENCES CLIENTE(id)
ON DELETE CASCADE,
CONSTRAINT fk_cs_suscripcion FOREIGN KEY (idSuscripcion)
REFERENCES SUSCRIPCION(id)
ON DELETE CASCADE
);

CREATE TABLE PAGO (
id INT AUTO_INCREMENT PRIMARY KEY,
fechaPago DATE NOT NULL,
metodoPago ENUM("tarjeta", "paypal") NOT NULL,
estado ENUM("pendiente", "completado", "fallido") NOT NULL
);

CREATE TABLE CLIENTE_PAGO (
idCliente INT NOT NULL,
idPago INT NOT NULL,
PRIMARY KEY (idCliente, idPago),
CONSTRAINT fk_cp_cliente FOREIGN KEY (idCliente)
REFERENCES CLIENTE(id)
ON DELETE CASCADE,
CONSTRAINT fk_cp_pago FOREIGN KEY (idPago)
REFERENCES PAGO(id)
ON DELETE CASCADE
);

CREATE TABLE PERFIL (
id INT AUTO_INCREMENT PRIMARY KEY,
idCliente INT NOT NULL,
CONSTRAINT fk_perfil_cliente FOREIGN KEY (idCliente)
REFERENCES CLIENTE(id)
ON DELETE CASCADE
);

CREATE TABLE CONTENIDO (
id INT AUTO_INCREMENT PRIMARY KEY,
titulo VARCHAR(200) NOT NULL,
descripcion TEXT,
duracion INT NOT NULL,
clasificacionEdad VARCHAR(10) NOT NULL,
portadaUrl VARCHAR(255),
videoUrl VARCHAR(255),
tipo ENUM('serie', 'pelicula', 'documental') NOT NULL
);

CREATE TABLE HISTORIAL (
idPerfil INT NOT NULL,
idContenido INT NOT NULL,
ultimaReproduccion DATETIME NOT NULL,
tiempoVisto INT NOT NULL,
PRIMARY KEY (idPerfil, idContenido),
CONSTRAINT fk_hist_perfil FOREIGN KEY (idPerfil) REFERENCES PERFIL(id)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT fk_hist_contenido FOREIGN KEY (idContenido) REFERENCES CONTENIDO(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE FAVORITO (
idPerfil INT NOT NULL,
idContenido INT NOT NULL,
fechaAgregado DATE NOT NULL,
PRIMARY KEY (idPerfil, idContenido),
CONSTRAINT fk_fav_perfil FOREIGN KEY (idPerfil) REFERENCES PERFIL(id)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT fk_fav_contenido FOREIGN KEY (idContenido) REFERENCES CONTENIDO(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE CALIFICACION (
idPerfil INT NOT NULL,
idContenido INT NOT NULL,
calificacion ENUM("me_gusta", "no_me_gusta", "sin_clasificar") DEFAULT "sin_clasificar" NOT NULL,
PRIMARY KEY (idPerfil, idContenido),
CONSTRAINT fk_calif_perfil FOREIGN KEY (idPerfil) REFERENCES PERFIL(id)
ON DELETE CASCADE
ON UPDATE CASCADE,
CONSTRAINT fk_calif_contenido FOREIGN KEY (idContenido) REFERENCES CONTENIDO(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);

CREATE TABLE GENERO (
id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
nombre VARCHAR(67) NOT NULL
);

CREATE TABLE CONTENIDO_GENERO (
idContenido INT NOT NULL,
idGenero INT NOT NULL,
CONSTRAINT fk_cc_cont FOREIGN KEY (idContenido) REFERENCES CONTENIDO(id)
ON DELETE CASCADE 
ON UPDATE CASCADE,
CONSTRAINT fk_cc_gen FOREIGN KEY (idGenero) REFERENCES GENERO(id)
ON DELETE CASCADE
ON UPDATE CASCADE
);